// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTRLeZzLcs5OTxMwGakSyQAHQ3hqfKMT0',
    appId: '1:413822446456:web:1e24e9d67cd210d258f68d',
    messagingSenderId: '413822446456',
    projectId: 'duty-track-4fba8',
    authDomain: 'duty-track-4fba8.firebaseapp.com',
    storageBucket: 'duty-track-4fba8.firebasestorage.app',
    measurementId: 'G-0FH54Z384N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyijbcRIpvCO0BD5PZlmvN04NhiMcQ5OQ',
    appId: '1:413822446456:android:1e3ee702e897a6fe58f68d',
    messagingSenderId: '413822446456',
    projectId: 'duty-track-4fba8',
    storageBucket: 'duty-track-4fba8.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtWJs7qb6QsGGOn2Yf8ijzj5PKYnBXAJA',
    appId: '1:413822446456:ios:bb9155a837323c0e58f68d',
    messagingSenderId: '413822446456',
    projectId: 'duty-track-4fba8',
    storageBucket: 'duty-track-4fba8.firebasestorage.app',
    iosBundleId: 'com.example.dutyTrack',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtWJs7qb6QsGGOn2Yf8ijzj5PKYnBXAJA',
    appId: '1:413822446456:ios:bb9155a837323c0e58f68d',
    messagingSenderId: '413822446456',
    projectId: 'duty-track-4fba8',
    storageBucket: 'duty-track-4fba8.firebasestorage.app',
    iosBundleId: 'com.example.dutyTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTRLeZzLcs5OTxMwGakSyQAHQ3hqfKMT0',
    appId: '1:413822446456:web:102aa1e5c94741d158f68d',
    messagingSenderId: '413822446456',
    projectId: 'duty-track-4fba8',
    authDomain: 'duty-track-4fba8.firebaseapp.com',
    storageBucket: 'duty-track-4fba8.firebasestorage.app',
    measurementId: 'G-V73C57NWNC',
  );
}
